# Generation of a csv file for downloading of IUPACs name related to the G9a inhibitors

### Content   <a name="content"></a>

1. [Load and analyse PubChem BioAssay data](#1)
2. [Create a data frame with CIDs and targets](#2)
3. [Reduce the inactive compounds](#3)
4. [Generate the csv file for IUPAC names dowloading](#4)

### Load and analyse PubChem BioAssay data <a name="1"></a>

In [1]:
import pandas as pd 

# load the PubChem AID 504332 bioassy dataset
# https://pubchem.ncbi.nlm.nih.gov/bioassay/504332
df = pd.read_csv('pubchem_G9a.csv', low_memory=False, on_bad_lines='skip')

# To avoid truncation of some columns during data frame display
pd.set_option('display.max_columns', None) 

# Display the data frame
print('Shape of the data frame: ', df.shape)
df.head()

Shape of the data frame:  (353737, 44)

,PUBCHEM_RESULT_TAG,SID,CID,PUBCHEM_EXT_DATASOURCE_SMILES,PUBCHEM_ACTIVITY_OUTCOME,PUBCHEM_ACTIVITY_SCORE,PUBCHEM_ACTIVITY_URL,PUBCHEM_ASSAYDATA_COMMENT,Phenotype,Potency,Efficacy,Analysis Comment,Curve_Description,Fit_LogAC50,Fit_HillSlope,Fit_R2,Fit_InfiniteActivity,Fit_ZeroActivity,Fit_CurveClass,Excluded_Points,Max_Response,Activity at 0.00366 uM,Activity at 0.00865 uM,Activity at 0.018 uM,Activity at 0.041 uM,Activity at 0.092 uM,Activity at 0.133 uM,Activity at 0.202 uM,Activity at 0.415 uM,Activity at 0.501 uM,Activity at 0.843 uM,Activity at 1.264 uM,Activity at 2.335 uM,Activity at 3.417 uM,Activity at 5.146 uM,Activity at 10.61 uM,Activity at 12.70 uM,Activity at 21.52 uM,Activity at 31.98 uM,Activity at 58.95 uM,Activity at 101.6 uM,Activity at 134.7 uM,Activity at 186.0 uM,Compound QC
0,154378,57257240,135953404.0,C#CCOCCOCCOCCNC1=NC(=NC(=N1)N2CCN(CC2)C(=O)CN3...,Inactive,0,NaN,NaN,Inactive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,4.0834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.8175,NaN,NaN,4.0834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,QC'd by Kevin Burgess - Texas A and M Univ. - ...
1,154349,57257238,135953403.0,CC(C)(C)C1=CC(=C(C(=C1)C(C)(C)C)O)C2=NC(=NC(=N...,Inactive,0,NaN,NaN,Inactive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,-9.2676,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.1391,NaN,NaN,-9.2676,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,QC'd by Elizabeth A Amin - Univ. of Minnesota ...
2,180795,57255498,135953402.0,CC[C@H](C)[C@@H](C(=O)N1CCN(CC1)C2=NC(=NC(=N2)...,Inactive,0,NaN,NaN,Inactive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,-2.6485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.5227,NaN,NaN,-2.6485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,QC'd by Kevin Burgess - Texas A and M Univ. - ...
3,180827,57255496,135953401.0,CC[C@H](C)[C@@H](C(=O)N1CCN(CC1)C2=NC(=NC(=N2)...,Inactive,0,NaN,NaN,Inactive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,8.8802,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0368,NaN,NaN,8.8802,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,QC'd by Kevin Burgess - Texas A and M Univ. - ...
4,180868,57255491,135953400.0,CCCCC1=CN(N=N1)[C@@H](CCCC[NH3+])C(=O)N2CCN(CC...,Inactive,0,NaN,NaN,Inactive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,-2.1811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.5293,NaN,NaN,-2.1811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,QC'd by Kevin Burgess - Texas A and M Univ. - ...

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 353737 entries, 0 to 353736
Data columns (total 44 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   PUBCHEM_RESULT_TAG             353737 non-null  int64
 1   SID                            353737 non-null  int64
 2   CID                            353732 non-null  float64
 3   PUBCHEM_EXT_DATASOURCE_SMILES  353732 non-null  object
 4   PUBCHEM_ACTIVITY_OUTCOME       353737 non-null  object
 5   PUBCHEM_ACTIVITY_SCORE         353737 non-null  int64
 6   PUBCHEM_ACTIVITY_URL           0 non-null       float64
 7   PUBCHEM_ASSAYDATA_COMMENT      0 non-null       float64
 8   Phenotype                      353737 non-null  object
 9   Potency                        91291 non-null   float64
 10  Efficacy                       91291 non-null   float64
 11  Analysis Comment               0 non-null       float64
 12  Curve_Description              95035 non-null   object
 13  Fit_LogAC50                    91291 non-null   float64
 14  Fit_HillSlope                  91291 non-null   float64
 15  Fit_R2                         91291 non-null   float64
 16  Fit_InfiniteActivity           91291 non-null   float64
 17  Fit_ZeroActivity               91291 non-null   float64
 18  Fit_CurveClass                 353737 non-null  float64
 19  Excluded_Points                290208 non-null  object
 20  Max_Response                   353737 non-null  float64
 21  Activity at 0.00366 uM         859 non-null     float64
 22  Activity at 0.00865 uM         0 non-null       float64
 23  Activity at 0.018 uM           3504 non-null    float64
 24  Activity at 0.041 uM           1029 non-null    float64
 25  Activity at 0.092 uM           316744 non-null  float64
 26  Activity at 0.133 uM           283 non-null     float64
 27  Activity at 0.202 uM           1042 non-null    float64
 28  Activity at 0.415 uM           33 non-null      float64
 29  Activity at 0.501 uM           323834 non-null  float64
 30  Activity at 0.843 uM           1180 non-null    float64
 31  Activity at 1.264 uM           12 non-null      float64
 32  Activity at 2.335 uM           322728 non-null  float64
 33  Activity at 3.417 uM           269 non-null     float64
 34  Activity at 5.146 uM           1071 non-null    float64
 35  Activity at 10.61 uM           48 non-null      float64
 36  Activity at 12.70 uM           311660 non-null  float64
 37  Activity at 21.52 uM           1120 non-null    float64
 38  Activity at 31.98 uM           12 non-null      float64
 39  Activity at 58.95 uM           296315 non-null  float64
 40  Activity at 101.6 uM           166993 non-null  float64
 41  Activity at 134.7 uM           31 non-null      float64
 42  Activity at 186.0 uM           1 non-null       float64
 43  Compound QC                    353737 non-null  object
dtypes: float64(35), int64(3), object(6)
memory usage: 118.7+ MB

In [3]:
# Remive missing values
df = df[df['CID'].notna()]
df.shape

(353732, 44)

In [4]:
# Remove duplicates without keeping a sample ofthem and reset the indexes 
df = df.drop_duplicates(subset='CID', keep=False).reset_index(drop=True)
df.shape

(343698, 44)

In [5]:
# Turn CID float data type into integer
df['CID'] = df['CID'].astype('int64')

In [6]:
# Filter inhibitors 
df = df[['CID',
         'SID',
         'PUBCHEM_ACTIVITY_OUTCOME']] 
df.shape # 646675

(343698, 3)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 343698 entries, 0 to 343697
Data columns (total 3 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   CID                       343698 non-null  int64
 1   SID                       343698 non-null  int64
 2   PUBCHEM_ACTIVITY_OUTCOME  343698 non-null  object
dtypes: int64(2), object(1)
memory usage: 7.9+ MB

[<a href="#content">Back to top</a>]

## Create a data frame with CIDs and targets <a name="2"></a>

In [8]:
df['PUBCHEM_ACTIVITY_OUTCOME'] = df['PUBCHEM_ACTIVITY_OUTCOME'].astype(str) 
# Get unique values from 'column1'
unique_values = df['PUBCHEM_ACTIVITY_OUTCOME'].unique()
unique_values

array(['Inactive', 'Inconclusive', 'Active'], dtype=object)

In [9]:
df.rename(columns={'PUBCHEM_ACTIVITY_OUTCOME':'target'}, inplace=True)

# Set the option to explicitly handle downcasting
pd.set_option('future.no_silent_downcasting', True)

# Create a mapping dictionary to replace string values with numeric values
mapping = {'Active': 1, 'Inactive': 0, 'Inconclusive':2}

# Replace string values with numeric values using the mapping dictionary
df['target'] = df['target'].replace(mapping)

# Display the data frame
print('Shape of the data frame: ', df.shape)
df.head()

Shape of the data frame:  (343698, 3)

         CID       SID target
0  135953404  57257240      0
1  135953403  57257238      0
2  135953402  57255498      0
3  135953401  57255496      0
4  135953400  57255491      0

In [10]:
# Turn CID float data type into integer
df['target'] = pd.to_numeric(df['target'])

In [11]:
df['target'].value_counts()

target
0    262848
2     50608
1     30242
Name: count, dtype: int64

In [12]:
df_1 = df[df['target']==1]
df_1.shape

(30242, 3)

[<a href="#content">Back to top</a>]

## Reduce the inactive compounds <a name="3"></a>

In [13]:
# load the water solunility data 
df_sol = pd.read_csv('pubchem_solubility.csv')

# Display the data frame
print('Shape of the data frame: ', df_sol.shape)
df_sol.head()

Shape of the data frame:  (57859, 30)

,PUBCHEM_RESULT_TAG,SID,CID,PUBCHEM_EXT_DATASOURCE_SMILES,OUTCOME,PUBCHEM_ACTIVITY_SCORE,PUBCHEM_ACTIVITY_URL,PUBCHEM_ASSAYDATA_COMMENT,Solubility at pH 7.4_Qualifier_Mean,Solubility at pH 7.4_Mean,Test Concentration_1,Solubility at pH 7.4_Qualifier_1,Solubility at pH 7.4_1,Solubility at pH 7.4_Comment_1,Solubility of Astemizole at pH 7.4_Qualifier_1,Solubility of Astemizole at pH 7.4_1,Solubility of Sulfamethizole at pH 7.4_Qualifier_1,Solubility of Sulfamethizole at pH 7.4_1,Solubility of Imipramine HCl at pH 7.4_Qualifier_1,Solubility of Imipramine HCl at pH 7.4_1,Test Concentration_2,Solubility at pH 7.4_Qualifier_2,Solubility at pH 7.4_2,Solubility at pH 7.4_Comment_2,Solubility of Astemizole at pH 7.4_Qualifier_2,Solubility of Astemizole at pH 7.4_2,Solubility of Sulfamethizole at pH 7.4_Qualifier_2,Solubility of Sulfamethizole at pH 7.4_2,Solubility of Imipramine HCl at pH 7.4_Qualifier_2,Solubility of Imipramine HCl at pH 7.4_2
0,1,24826444,2374148,COC1=CC=C(C=C1)OCC2=NNC(=S)N2N,Active,40,NaN,NaN,=,10.85,200,<,0.1,Below LOQ,=,14.2,>,40.5,>,47.5,200.0,=,21.6,NaN,=,27.7,>,40.5,>,47.5
1,2,49669186,5295761,CC1=CC(=C(C=C1)NC2=NC3=CC=CC=C3N4C2=NN=C4)Cl,Inactive,0,NaN,NaN,<,0.10,200,<,0.1,Below LOQ,=,12.3,>,40.5,>,47.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,49669768,22431387,CC1=CC(=CC=C1)CCNC2=NC3=C(C=C(C=C3)C)N4C2=NN=C4,Inactive,0,NaN,NaN,<,0.10,200,<,0.1,Below LOQ,=,12.3,>,40.5,>,47.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,8139962,14296,CC1=C(N=C(C(=N1)C)C)C,Inactive,0,NaN,NaN,<,0.10,200,<,0.1,Below LOQ,=,11.4,>,40.5,>,47.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,24803435,865684,CC1=CC2=NC(=C(C=C2C=C1)C#N)NC3=CC=CC=C3OC,Inactive,0,NaN,NaN,<,0.20,200,<,0.2,Below LOQ,=,11.4,>,40.5,>,47.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Keep only the CID values 
df_sol = df_sol["CID"]

# Reduce values keeping only the common for both datasets CID
df = pd.merge(df, df_sol, on="CID")

# Display the data frame
print('Shape of the data frame: ', df_sol.shape)

Shape of the data frame:  (57859,)

In [15]:
df['target'].value_counts()

target
0    33554
2     4969
1     4204
Name: count, dtype: int64

In [16]:
# CSeparate target 0 compounds
df_0 = df[df['target']==0]

# Display the data frame
print('Shape of df_0: ', df_0.shape)

Shape of df_0:  (33554, 3)

In [17]:
# Concatenate target 1 and 0 compounds 
df = pd.concat([df_0, df_1])

In [18]:
# Count each of the binary targets
df['target'].value_counts()

target
0    33554
1    30242
Name: count, dtype: int64

In [19]:
# Shuffle the resulting data set
df = df.sample(
    frac = 1,        # Return entire dataframe
    random_state=1   # Make result reproducible
    ).reset_index(drop=True)

# Display the data frame
print('Shape of df: ', df.shape)

Shape of df:  (63796, 3)

[<a href="#content">Back to top</a>]

## Generate a csv file with CIDs and targets for IUPAC names dowloading  <a name="4"></a>

In [20]:
df.to_csv('CIDs_targets_G9a.csv')

[<a href="#content">Back to top</a>]